title: Teemu Pöyhönen
logo: /profilepic.jpg
description: LLMs, evaluation, and agentic NLP
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
cv_url: /Teemu-Poyhonen-CV.pdf
email: poyhonenteemu@gmail.com
