title: Teemu Pöyhönen
logo: /profilepic.jpg
description: LLMs, evaluation, and agentic systems
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
cv_url: /Teemu-Poyhonen-CV.pdf
email: poyhonenteemu@gmail.com
url: https://teemursu.github.io
lang: en
keywords:
  - Teemu Pöyhönen
  - LLMs
  - evaluation
  - agentic systems
  - generative AI
  - Helsinki
  - research
  - longboard dancing
  - music
  - photography
  - games
